name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  deploy_martin:
    runs-on: [self-hosted, martin]  # Ejecutar en el runner de Martín

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Copiar los archivos al directorio de trabajo del runner (grupodiseno) en la instancia
      - name: Sync application code
        run: |
          rsync -av --progress --exclude='.git' * /home/ubuntu/actions-runner/_work/grupodiseno/
          echo "Synced files to /home/ubuntu/actions-runner/_work/grupodiseno/"

      # Paso 3: Listar archivos para asegurar que 'index.html' esté en su lugar
      - name: List files in application directory
        run: |
          ls -la /home/ubuntu/actions-runner/_work/grupodiseno/
          echo "Listed files in /home/ubuntu/actions-runner/_work/grupodiseno/"

      # Paso 4: Recargar Nginx para reflejar los cambios
      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx  # Recarga la configuración de Nginx para aplicar cambios
          echo "Reloaded Nginx"

      # Paso 5: Verificar que el archivo 'index.html' esté en la ubicación correcta en el servidor web
      - name: Verify deployed index.html
        run: |
          if [ -f /home/ubuntu/actions-runner/_work/grupodiseno/index.html ]; then 
            echo "Deployed index.html found. Verification successful.";
          else 
            echo "Deployed index.html not found. Verification failed."; 
            exit 1; 
          fi

  deploy_felix:
    runs-on: [self-hosted, felix]  # Ejecutar en el runner de Félix

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Copiar los archivos al directorio de trabajo del runner (grupodiseno) en la instancia
      - name: Sync application code
        run: |
          rsync -av --progress --exclude='.git' * /home/ubuntu/actions-runner/_work/grupodiseno/
          echo "Synced files to /home/ubuntu/actions-runner/_work/grupodiseno/"

      # Paso 3: Listar archivos para asegurar que 'index.html' esté en su lugar
      - name: List files in application directory
        run: |
          ls -la /home/ubuntu/actions-runner/_work/grupodiseno/
          echo "Listed files in /home/ubuntu/actions-runner/_work/grupodiseno/"

      # Paso 4: Recargar Nginx para reflejar los cambios
      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx  # Recarga la configuración de Nginx para aplicar cambios
          echo "Reloaded Nginx"

      # Paso 5: Verificar que el archivo 'index.html' esté en la ubicación correcta en el servidor web
      - name: Verify deployed index.html
        run: |
          if [ -f /home/ubuntu/actions-runner/_work/grupodiseno/index.html ]; then 
            echo "Deployed index.html found. Verification successful.";
          else 
            echo "Deployed index.html not found. Verification failed."; 
            exit 1; 
          fi

  deploy_dylan:
    runs-on: [self-hosted, dylan]  # Ejecutar en el runner de Dylan

    steps:
      # Paso 1: Checkout del código desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Copiar los archivos al directorio de trabajo del runner (grupodiseno) en la instancia
      - name: Sync application code
        run: |
          rsync -av --progress --exclude='.git' * /home/ubuntu/actions-runner/_work/grupodiseno/
          echo "Synced files to /home/ubuntu/actions-runner/_work/grupodiseno/"

      # Paso 3: Listar archivos para asegurar que 'index.html' esté en su lugar
      - name: List files in application directory
        run: |
          ls -la /home/ubuntu/actions-runner/_work/grupodiseno/
          echo "Listed files in /home/ubuntu/actions-runner/_work/grupodiseno/"

      # Paso 4: Recargar Nginx para reflejar los cambios
      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx  # Recarga la configuración de Nginx para aplicar cambios
          echo "Reloaded Nginx"

      # Paso 5: Verificar que el archivo 'index.html' esté en la ubicación correcta en el servidor web
      - name: Verify deployed index.html
        run: |
          if [ -f /home/ubuntu/actions-runner/_work/grupodiseno/index.html ]; then 
            echo "Deployed index.html found. Verification successful.";
          else 
            echo "Deployed index.html not found. Verification failed."; 
            exit 1; 
          fi

